### ISSUE TITLE
Missing text in drafts

### ISSUE THREAD

**Issue by uskka** [katalysteducation/cnx-designer#11]
At the bottom of the page there is a big block of text that is missing in drafts.
Types of Treatment - https://adaptarr.naukosfera.com/modules/c5913a66-3ee5-4c30-bc6c-65c2c536cb86

**Comment by aiwenar** [comment]
Only issues with drafts (https://adaptarr.naukosfera.com/drafts/*) are related to this repository, report the rest either in [katalysteducation/adaptarr-front](https://github.com/katalysteducation/adaptarr-front) or on trello.
